# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('strike_num', models.IntegerField(default=20)),
                ('hr_num', models.IntegerField(default=25)),
                ('single_num', models.IntegerField(default=35)),
                ('double_num', models.IntegerField(default=40)),
                ('triple_num', models.IntegerField(default=44)),
                ('hbp_num', models.IntegerField(default=45)),
            ],
        ),
    ]
